# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
